name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there! 👋 Thanks for opening an issue! We appreciate your input and will do our best to address it"
        pr-message: "Hello! 👋 Thanks for the pull request! Your changes are valuable, and we'll review them as soon as possible"
